'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

fib_list = [1, 2, 3]
a = fib_list[0]
b = fib_list[1]
c = fib_list[2]
prev_num = a
num = b
next_num = c
add_num = 0

while num < 4000000:
    print(num)
    num = prev_num+num
    prev_num = num-prev_num
    next_num = num+prev_num
    fib_list.append(next_num)
    a = fib_list[+1]
    b = fib_list[+1]
    c = fib_list[+1]

for n in fib_list:
    if n in range(0, 4000000, 2):
        add_num += n

print('This is the added number of all the even fibonacci numbers', add_num)
